# Tweet Sentiment Classification

A three-class tweet sentiment classification workflow using TF-IDF features and Multinomial Naive Bayes.

Run this notebook in Google Colab or a local Jupyter environment after following the setup instructions in the repository README.

In [ ]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
import os
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics

In [ ]:
#Getting Data source
!pip install -q kaggle

In [ ]:
# For Google Colab, upload kaggle.json through the Files panel, then run:
# !mkdir -p ~/.kaggle && mv kaggle.json ~/.kaggle/kaggle.json && chmod 600 ~/.kaggle/kaggle.json
# See README.md for local environment setup.

Mounted at /content/gdrive

In [ ]:
# Kaggle reads credentials from ~/.kaggle/kaggle.json by default.

In [ ]:
os.makedirs("data", exist_ok=True)
!kaggle datasets download -d sahideseker/tweet-sentiment-classification-dataset -p data --unzip

Dataset URL: https://www.kaggle.com/datasets/sahideseker/tweet-sentiment-classification-dataset
License(s): CC-BY-SA-4.0

In [ ]:
# Dataset is extracted into the local data/ directory by the command above.

Archive:  /content/tweet-sentiment-classification-dataset.zip
  inflating: tweet_sentiment.csv

In [ ]:
path = "data/tweet_sentiment.csv"
df = pd.read_csv(path)
df

                             tweet sentiment
0        The event starts at 5 PM.   neutral
1      I hate how this turned out.  negative
2            Fantastic experience!  positive
3            Fantastic experience!  positive
4    This is the worst thing ever!  negative
..                             ...       ...
995           It’s cloudy outside.   neutral
996         Great job by the team!  positive
997   I'm so happy about the news!  positive
998        It ruined my whole day.  negative
999    I'm sick of this happening.  negative

[1000 rows x 2 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   tweet      1000 non-null   object
 1   sentiment  1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [ ]:
def transfrom_sentiment_to_number(text):
  if text == "positive":
    return 2
  elif text == "negative":
    return 1
  else:
    return 0

In [ ]:
df['n_sentiment'] = df['sentiment'].apply(transfrom_sentiment_to_number)
df

                             tweet sentiment  n_sentiment
0        The event starts at 5 PM.   neutral            0
1      I hate how this turned out.  negative            1
2            Fantastic experience!  positive            2
3            Fantastic experience!  positive            2
4    This is the worst thing ever!  negative            1
..                             ...       ...          ...
995           It’s cloudy outside.   neutral            0
996         Great job by the team!  positive            2
997   I'm so happy about the news!  positive            2
998        It ruined my whole day.  negative            1
999    I'm sick of this happening.  negative            1

[1000 rows x 3 columns]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(df['tweet'], df['n_sentiment'], test_size = 0.2, random_state = 42)

In [ ]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((800,), (200,), (800,), (200,))

In [ ]:
tf_idf = TfidfVectorizer(stop_words='english')
X_train_tf = tf_idf.fit_transform(X_train.tolist())
X_test_tf = tf_idf.transform(X_test.tolist())

In [ ]:
X_train_tf.shape, X_test_tf.shape

((800, 37), (200, 37))

In [ ]:
naive_bayes_classifier = MultinomialNB()
naive_bayes_classifier.fit(X_train_tf, y_train)

MultinomialNB()

In [ ]:
predict = naive_bayes_classifier.predict(X_test_tf)

In [ ]:
target_names = ['neutral', 'negative', 'positive']
print(metrics.classification_report(y_test, predict,target_names=target_names))

              precision    recall  f1-score   support

     neutral       1.00      1.00      1.00        67
    negative       1.00      1.00      1.00        55
    positive       1.00      1.00      1.00        78

    accuracy                           1.00       200
   macro avg       1.00      1.00      1.00       200
weighted avg       1.00      1.00      1.00       200